include $(APSIM)/Model/Build/Platform.make

ifeq ($(PLATFORM),Linux)
PROJECT = SugarCane
else
PROJECT = SugarCane
endif

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)DOTNET.make
