include $(APSIM)/Model/Build/Platform.make

PROJECT = WaterSupply

SRC = Registrations.f90 WaterSupply.f90
STATICLIBS = FortranInfrastructure
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

