include $(APSIM)/Model/Build/Platform.make

SRC = ApsimAttributes.cpp \
   ApsimComponent.cpp \
   AssemblyInfo.cpp \
   ComponentType.cpp \
   EntryPoints.cpp \
   Factory.cpp \
   FactoryEvent.cpp \
   FactoryProperty.cpp \
   Instance.cpp \
   MessageData.cpp \
   PaddockType.cpp \
   Stdafx.cpp \
   VariableType.cpp

PROJECT = DOTNETComponentInterface

PROJECTTYPE = dll
RESOBJ = dllres.res

include $(APSIM)/Model/Build/$(PLATFORM)DOTNET.make
