include $(APSIM)/Model/Build/Platform.make

SRC = ApsimAttributes.cpp \
   ApsimComponent.cpp \
   AssemblyInfo.cpp \
   Component.cpp \
   ../DataTypes/DOTNETDataTypes.cpp \
   EntryPoints.cpp \
   Factory.cpp \
   FactoryEvent.cpp \
   FactoryProperty.cpp \
   GenericType.cpp \
   Instance.cpp \
   MessageData.cpp \
   Paddock.cpp \
   LinkField.cpp \
   RunTimeEventHandler.cpp \
   Stdafx.cpp \
   Variable.cpp 

PROJECT = DOTNETComponentInterface

PROJECTTYPE = dll
RESOBJ = dllres.res

include $(APSIM)/Model/Build/$(PLATFORM)DOTNET.make
