include $(APSIM)/Model/Build/Platform.make

PROJECT = ConToSim

SRC = ConToSim.cpp ControlFileConverter.cpp

LIBS = General ApsimShared
PROJECTTYPE = exe

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make
