include $(APSIM)/Model/Build/Platform.make

PROJECT = Grasp

SRC = Registrations.f90 Grasp.for
STATICLIBS = FortranInfrastructure
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make
