include $(APSIM)/Model/Build/Platform.make

PROJECT = Grasp

SRC = Registrations.f90 Grasp.for
STATICLIBS = FortranInfrastructure
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make
