include $(APSIM)/Model/Build/Platform.make

PROJECT = SiloInput

SRC = SiloInput.cpp SiloInputComponent.cpp
LIBS = General ApsimShared ComponentInterface Input
OBJS = $(APSIM)/Model/ComponentInterface/EntryPoints.obj

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

