include $(APSIM)/Model/Build/Platform.make

PROJECT = SiloInput

SRC = SiloInput.cpp SiloInputComponent.cpp  ..\ComponentInterface\EntryPoints.cpp
LIBS = General ApsimShared ComponentInterface Input

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

