include $(APSIM)/Model/Build/Platform.make

PROJECT = General

SRC =   date_class.cpp		\
	math_functions.cpp	\
	stream_functions.cpp	\
	string_functions.cpp	\
	StringTokenizer.cpp	\
	stristr.cpp		\
	macro.cpp		\
	io_functions.cpp	\
	xml.cpp			\
	path.cpp		\
	IniFile.cpp 		\
	stream_processor.cpp    \
	dll.cpp			\
	http.cpp   \
	strptime.cpp

PROJECTTYPE=libdll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make
