#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <math.h>
#include <General/stl_functions.h>
#include <General/string_functions.h>
#include <General/stream_functions.h>
#include <General/path.h>
#include <General/xml.h>
