include $(APSIM)/Model/Build/Platform.make

PROJECT = Surface

SRC = Registrations.f90 Surface.for
STATICLIBS = FortranInfrastructure
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

