include $(APSIM)/Model/Build/Platform.make

PROJECT = Growth

SRC = Registrations.f90 Growth.for
STATICLIBS = FortranInfrastructure CropTemplate
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make


