include $(APSIM)/Model/Build/Platform.make

PROJECT = Test

SRC = testComponentInterface.cpp \
      TestVariables.cpp \
      TestParameters.cpp \
      TestEvents.cpp \
      TestMisc.cpp

LIBS = General ApsimShared ComponentInterface2 C:\Progra~1\Borland\CBuilder6\Components\Boost\libs\test\Test
PROJECTTYPE = exe


include $(APSIM)/Model/Build/$(PLATFORM)CPP.make


