include $(APSIM)/Model/Build/Platform.make

PROJECT = Test

SRC = testComponentInterface.cpp \
      TestVariables.cpp \
      TestParameters.cpp \
      TestEvents.cpp \
      TestMisc.cpp

LIBS = General ApsimShared ComponentInterface2 cppunit_dll

PROJECTTYPE = exe


include $(APSIM)/Model/Build/$(PLATFORM)CPP.make


