#! /usr/bin/tclsh

# convert a ir72.crp file (in oryza format) to xml for apsim

set fp [open IR72.CRP r]

set state {}; set abuffer ""; set cbuffer ""
while {[gets $fp line] >= 0} {
  if {[string index $line 0] == "*"} {
    set newstate comment
    append cbuffer [string range $line 1 end]\n
    set line ""

  } elseif {[regexp -all {^(\s*!)(.*?)} $line junk comment]} {
    set newstate comment
    append cbuffer [string range $line 1 end]\n
    set line ""

  } elseif {[regexp -all {^(\s*)([A-Za-z0-9]+)(\s*\=\s*)(\-*[0-9\.]+)(\s*!)(.*?)} $line junk junk var junk value junk comment]} {
    set newstate variable
    set line "<$var description=\"$comment\">$value</$var>"

  } elseif {[regexp -all {^(\s*)([A-Za-z0-9]+)(\s*\=\s*\')([A-Za-z0-9]+)(\'\s*!)(.*?)} $line junk junk var junk value junk comment]} {
    set newstate variable
    set line "<$var description=\"$comment\">$value</$var>"

  } elseif {[regexp -all {^(\s*)([A-Za-z0-9]+)(\s*\=\s*)(\-*[0-9\.]+)(\s*,\s*)(\-*[0-9\.]+)(\s*,\s*)} $line junk junk var junk value1 junk value2]} {
    set newstate array
    set abuffer "<$var description=\"\">$value1 $value2"
    set arrayvar $var
    set line ""

  } elseif {[regexp -all {^(\s*)(\-*[0-9\.]+)(\s*,\s*)(\-*[0-9\.]+)(\s*,*\s*)} $line junk junk value1 junk value2 junk] } {
    append abuffer " $value1 $value2"
    set line ""

   }
   if {$state == "array" && $state != $newstate} {
     puts "$abuffer</$arrayvar>"
     set abuffer ""
   }
   if {$state == "comment" && $state != $newstate} {
     puts "<!--$cbuffer-->"
     set cbuffer ""
   }
   if {$line != ""} {
     puts $line
   }
   set state $newstate
}
if {$state == "array" } {
     puts "$abuffer</$arrayvar>"
}
if {$state == "comment"} {
     puts "<!--$cbuffer-->"
}

close $fp
