include $(APSIM)/Model/Build/Platform.make

PROJECT = Oryza

SRC = Registrations.f90 Oryza.for
STATICLIBS = FortranInfrastructure
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

