include $(APSIM)/Model/Build/Platform.make

PROJECT = Sugar

SRC = Registrations.f90 SugarMain.for
STATICLIBS = FortranInfrastructure CropTemplate
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

