include $(APSIM)/Model/Build/Platform.make

PROJECT = ProtocolManager

SRC = ProtocolManager.cpp Coordinator.cpp ComponentAlias.cpp ../ComponentInterface/EntryPoints.cpp
LIBS = General ApsimShared Protocol ComponentInterface

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

