include $(APSIM)/Model/Build/Platform.make

PROJECT = Tree

SRC = Registrations.f90 Tree.for
STATICLIBS = FortranInfrastructure
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

