include $(APSIM)/Model/Build/Platform.make

ifeq ($(PLATFORM),Linux)
PROJECT = SoilWater2
else
PROJECT = SoilWater2
endif

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)DOTNET.make
