include $(APSIM)/Model/Build/Platform.make

PROJECT = SupplementScienceConverter

SRC = SupplementConverter.cpp SupplementScienceConverter.cpp
LIBS = General ApsimShared ComponentInterface
OBJS = $(APSIM)/Model/ComponentInterface/EntryPoints.obj

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make


