include $(APSIM)/Model/Build/Platform.make

PROJECT = SupplementScienceConverter

SRC = SupplementConverter.cpp SupplementScienceConverter.cpp ..\ComponentInterface\EntryPoints.cpp
LIBS = General ApsimShared ComponentInterface

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make


