*     ================================================================
*      maximum_number_of_soil_layers
*     ================================================================

*   Short description:
*      Array size specifier for all soil information

*   Changes:
*      020597 nih
* ----------------------- Declaration section ------------------------

*   Constant values

      integer    crop_max_layer 
      parameter (crop_max_layer = 100)

