include $(APSIM)/Model/Build/Platform.make

PROJECT = CropTemplate

SRC = crp_util.for \
      crp_root.for \
      crp_watr.for \
      crp_biom.for \
      crp_cnpy.for \
      crp_comm.for \
      crp_fail.for \
      crp_nitn.for \
      crp_phen.for \
      crp_temp.for \
      CropLibrary.for

PROJECTTYPE = lib

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

