include $(APSIM)/Model/Build/Platform.make

ifeq ($(PLATFORM),Linux)
PROJECT = SlopeEffectsOnWeather
else
PROJECT = SlopeEffectsOnWeather
endif

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)DOTNET.make
