include $(APSIM)/Model/Build/Platform.make

PROJECT = Irrigation

SRC = Registrations.f90 Irrigation.for
STATICLIBS = FortranInfrastructure
LIBS = FortranComponentInterface
DEF = Irrigation.def

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make


