include $(APSIM)/Model/Build/Platform.make

PROJECT = PatchInput

SRC = PatchInput.cpp PatchInputComponent.cpp 
LIBS = General ApsimShared ComponentInterface Input
OBJS = $(APSIM)/Model/ComponentInterface/EntryPoints.obj

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

