include $(APSIM)/Model/Build/Platform.make

PROJECT = PatchInput

SRC = PatchInput.cpp PatchInputComponent.cpp ..\ComponentInterface\EntryPoints.cpp 
LIBS = General ApsimShared ComponentInterface Input

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

