version = 6.1
[apsim.dbg]
title = Simple Debugger
module = clock   %apsuite/apsim/wheat/sample/wheat.par [sample] %apsuite/apsim/clock/clock.xml [standard]
module = input(met)       %apsuite/apsim/met/sample/dalby.met [weather]
module = report           %apsuite/apsim/wheat/sample/wheat.par [sample]
module = manager         %apsuite/apsim/wheat/sample/wheat.par [sample]
module = soilwat2   %apsuite/apsim/soilwat2/sample/soilwat2.par [black_earth] %apsuite/apsim/soilwat2/soilwat2.xml [standard]
module = soiln2   %apsuite/apsim/soiln2/sample/soiln2.par [black_earth] %apsuite/apsim/soiln2/soiln2.xml [standard]
module = plant(wheat)   %apsuite/apsim/wheat/sample/wheat.par [sample] %apsuite/apsim/wheat/wheat.xml [standard]
module = TclLink          tcllink.par [dbg]


