include $(APSIM)/Model/Build/Platform.make

PROJECT = VenLink

SRC = VenLink.cpp VensimComponent.cpp
LIBS = ApsimShared General ComponentInterface
OBJS = $(APSIM)/Model/ComponentInterface/EntryPoints.obj

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make
