include $(APSIM)/Model/Build/Platform.make

PROJECT = VenLink

SRC = VenLink.cpp VensimComponent.cpp  ..\ComponentInterface\EntryPoints.cpp
LIBS = ApsimShared General ComponentInterface

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make
