include $(APSIM)/Model/Build/Platform.make

PROJECT = Accum

SRC = Registrations.f90 accum.for
STATICLIBS = FortranInfrastructure
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make
