include $(APSIM)/Model/Build/Platform.make

PROJECT = Ozcot

SRC = Ozcot.for
STATICLIBS = FortranInfrastructure CropTemplate
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

