include $(APSIM)/Model/Build/Platform.make

PROJECT = Map

SRC = Registrations.f90 Map.for
STATICLIBS = FortranInfrastructure
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

