include $(APSIM)/Model/Build/Platform.make

PROJECT = Report

SRC = Report.cpp ReportComponent.cpp
LIBS = ComponentInterface2 ApsimShared General 
OBJS = $(APSIM)/Model/ComponentInterface2/CMPComponentEntryPoints.obj

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

