include $(APSIM)/Model/Build/Platform.make

PROJECT = Report

SRC = Report.cpp ReportComponent.cpp ../ComponentInterface2/CMPComponentEntryPoints.cpp
LIBS = General ApsimShared ComponentInterface2

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

