include $(APSIM)/Model/Build/Platform.make

PROJECT = Test

SRC = Test.cpp TestHttp.cpp TestXml.cpp TestIoFunctions.cpp \
      TestDateClass.cpp TestMathFunctions.cpp \
      TestStringFunctions.cpp \
      TestPathClass.cpp 


LIBS = General cppunit_dll
PROJECTTYPE = exe

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make


