include $(APSIM)/Model/Build/Platform.make

PROJECT = Log

SRC = Log.cpp LogComponent.cpp ../ComponentInterface/EntryPoints.cpp
LIBS = General ApsimShared Protocol ComponentInterface

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

