include $(APSIM)/Model/Build/Platform.make

PROJECT = Log

SRC = Log.cpp LogComponent.cpp
LIBS = General ApsimShared Protocol ComponentInterface

PROJECTTYPE = dll

OBJS = $(APSIM)/Model/ComponentInterface/EntryPoints.obj

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

