include $(APSIM)/Model/Build/Platform.make

PROJECT = Graz

SRC = Graz.cpp GrazComponent.cpp
STATICLIBS = FortranInfrastructure
LIBS = General ApsimShared ComponentInterface2

PROJECTTYPE = dll

OBJS = $(APSIM)/Model/ComponentInterface2/CMPComponentEntryPoints.obj


include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

