include $(APSIM)/Model/Build/Platform.make

PROJECT = Graz

SRC = Graz.cpp GrazComponent.cpp ../ComponentInterface2/CMPComponentEntryPoints.cpp
STATICLIBS = FortranInfrastructure
LIBS = General ApsimShared ComponentInterface2

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

