include $(APSIM)/Model/Build/Platform.make

PROJECT = SoilP

SRC = Registrations.f90 SoilP.f90
STATICLIBS = FortranInfrastructure
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

