include $(APSIM)/Model/Build/Platform.make

PROJECT = SoilN

SRC = SoilN.for
STATICLIBS = FortranInfrastructure
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

