include $(APSIM)/Model/Build/Platform.make

PROJECT = SOI

SRC = Registrations.f90 SOI.for
STATICLIBS = FortranInfrastructure
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

