include $(APSIM)/Model/Build/Platform.make

PROJECT = SysBal

SRC = Registrations.f90 SysBal.for
STATICLIBS = FortranInfrastructure
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

