include $(APSIM)/Model/Build/Platform.make

PROJECT = SysBal

SRC = Registrations.f90 SysBal.for
STATICLIBS = FortranInfrastructure
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

