include $(APSIM)/Model/Build/Platform.make

PROJECT = SWIM2

SRC = Registrations.f90 ApsimSwim.for
STATICLIBS = FortranInfrastructure
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make
