include $(APSIM)/Model/Build/Platform.make

PROJECT = Millet

SRC = Registrations.f90 MilletMain.for

STATICLIBS = FortranInfrastructure CropTemplate
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

