include $(APSIM)/Model/Build/Platform.make

ifeq ($(PLATFORM),Linux)
PROJECT = SoilWater
else
PROJECT = SoilWater
endif

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)DOTNET.make
