include $(APSIM)/Model/Build/Platform.make

PROJECT = SoilWat

SRC = Evap.for Lateral.for SoilWat.for 
STATICLIBS = FortranInfrastructure
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

