include $(APSIM)/Model/Build/Platform.make

PROJECT = Eo

SRC = Registrations.f90 eo.for 
STATICLIBS = FortranInfrastructure
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make
