include $(APSIM)/Model/Build/Platform.make

PROJECT = Solute

SRC = Registrations.f90 Solute.for
STATICLIBS = FortranInfrastructure
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

