include $(APSIM)/Model/Build/Platform.make

PROJECT = Solute

SRC = Registrations.f90 Solute.for
STATICLIBS = FortranInfrastructure
LIBS = ComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

