include $(APSIM)/Model/Build/Platform.make

PROJECT = Pond

SRC = Registrations.f90 Pond.f90
STATICLIBS = FortranInfrastructure
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make

