
include $(APSIM)/Model/Build/Platform.make

PROJECT = RunTime

PROJECTTYPE = bin

dummy:
	copy /Y $(APSIM)\Model\RunTime\*.* $(APSIM)\Model
# If compiling everything from source (ie not copied to runtime dir):
#	copy /Y $(APSIM)\..\BuildLibraries\hdf5-1.8.6\dll\zlib1.dll $(APSIM)\Model
#	copy /Y $(APSIM)\..\BuildLibraries\hdf5-1.8.6\dll\szip.dll $(APSIM)\Model
#	copy /Y $(APSIM)\..\BuildLibraries\hdf5-1.8.6\dll\hdf5_hldll.dll $(APSIM)\Model
#	copy /Y $(APSIM)\..\BuildLibraries\hdf5-1.8.6\dll\hdf5dll.dll $(APSIM)\Model
#	copy /Y $(APSIM)\..\BuildLibraries\netcdf-4.1.1\win32\NET\Release\netcdf.dll $(APSIM)\Model
#	copy /Y $(APSIM)\..\BuildLibraries\libxml2-2.7.7.win32\lib\libxml2.dll $(APSIM)\Model
#	copy /Y $(APSIM)\..\BuildLibraries\libiconv-1.11.1.win32\bin\iconv.dll $(APSIM)\Model


