include $(APSIM)/Model/Build/Platform.make

PROJECT = YieldProphet

SRC = YPComponent.cpp YPCalc.cpp ..\ComponentInterface\EntryPoints.cpp
LIBS = General ApsimShared ComponentInterface

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make
