include $(APSIM)/Model/Build/Platform.make

PROJECT = YieldProphet

SRC = YPComponent.cpp YPCalc.cpp
LIBS = General ApsimShared ComponentInterface
OBJS = $(APSIM)/Model/ComponentInterface/EntryPoints.obj

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make
