include $(APSIM)/Model/Build/Platform.make

PROJECT = ApsVis

SRC =    about.cpp \
         apsim_binary_table.cpp \
         Apsim_depth_chart.cpp \
         apsim_depth_table.cpp \
         apsim_table.cpp \
         APSVis.cpp \
         axis.cpp \
         Bar_format.cpp \
         Bar_series.cpp \
         brush.cpp \
         chart_child.cpp \
         chart.cpp \
         Chart_base.cpp \
         chart_types.cpp \
         data.cpp \
         database.cpp \
         depth_child.cpp \
         Depth_chart.cpp \
         drawable.cpp \
         filter.cpp \
         font.cpp \
         Format_base.cpp \
         freq_child.cpp \
         Frequency_chart.cpp \
         High_level_chart_base.cpp \
         High_level_screen.cpp \
         Legend_class.cpp \
         line.cpp \
         main.cpp \
         no_date.cpp \
         pen.cpp \
         plot.cpp \
         position.cpp \
         Pred_obs_chart.cpp \
         Prob_chart.cpp \
         prob_child.cpp \
         Rectangle.cpp \
         scatter_child.cpp \
         scatter_prop_form.cpp \
         Scatter_chart.cpp \
         Scatter_format.cpp \
         screen.cpp \
         Series_base.cpp \
         Table_base.cpp \
         Table_stream.cpp \
         TDepth_prop_form.cpp \
         text.cpp \
         TFreq_prop_form.cpp \
         TProb_prop_form.cpp \
         XY_series.cpp

LIBS = General ApsimShared
PROJECTTYPE = exe
VCL = yes
RES = APSVis.res


include $(APSIM)/Model/Build/$(PLATFORM)CPP.make
