include $(APSIM)/Model/Build/Platform.make

PROJECT = Test

SRC = test.cpp \
      testControlFileConverter.cpp \
      testApsimControlFile.cpp \
      testApsimDataFile.cpp \
      $(APSIM)\Model\ConToSim\ControlFileConverter.cpp

LIBS = General ApsimShared C:\Progra~1\Borland\CBuilder6\Components\Boost\libs\test\Test
PROJECTTYPE = exe


include $(APSIM)/Model/Build/$(PLATFORM)CPP.make


