


namespace ApsimFile

{

    public class ComponentUtility
    {

        public static string CalcFileName(Component Data)
        {
            // ----------------------------------- 
            // Get an autogenerated output/summary 
            // file name for specified node. 
            // NB The returned filename won't have 
            // a path. 
            // ----------------------------------- 

            string SimulationName = null;
            string PaddockName = null;
            Component D = Data;
            //temp component variable (set it to the parameter passed in [starting component]) 

            //loop back up the component datastructure until you get to the root component. 
            while ((D.Parent != null))
            {
                D = D.Parent;
                if (D.Type.ToLower() == "area")
                {
                    PaddockName = D.Name;
                    //store the paddock name for later 
                }
                else if (D.Type.ToLower() == "simulation")
                {
                    SimulationName = D.Name;
                    //store the simulation name for later 
                }
            }

            string FileName = SimulationName;
            //start out with the filename just being the simulation name 
            //if there was a paddock component and it had been renamed by the user. 
            if ((PaddockName != null) && PaddockName.ToLower() != "paddock")
            {
                FileName = FileName + " " + PaddockName;
                //add the paddock name to the simulation name 
            }
            //if the starting component (either an outputfile or summary file) has been renamed by the user 
            if (Data.Name.ToLower() != "outputfile" & Data.Name.ToLower() != "summaryfile")
            {
                FileName = FileName + " " + Data.Name;
                //add the starting component name to the simulation name 
            }
            //add the correct file suffix 
            if (Data.Type == "summaryfile")
            {
                FileName = FileName + ".sum";
            }
            else
            {
                FileName = FileName + ".out";
            }

            return FileName;
        }

    }

}

