include $(APSIM)/Model/Build/Platform.make

PROJECT = Tracker

SRC = Tracker.cpp TrackerComponent.cpp TrackerVariable.cpp ..\ComponentInterface\EntryPoints.cpp
LIBS = General ApsimShared ComponentInterface

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make
