include $(APSIM)/Model/Build/Platform.make

PROJECT = Tracker

SRC = Tracker.cpp TrackerComponent.cpp TrackerVariable.cpp
LIBS = General ApsimShared ComponentInterface
OBJS = $(APSIM)/Model/ComponentInterface/EntryPoints.obj

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make
