
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Entry password;
	
	private global::Gtk.Entry username;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.RadioButton radiobutton1;
	
	private global::Gtk.RadioButton radiobutton2;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Entry fileEntry;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Entry dirEntry;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Entry simsPerJobEntry;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Entry hoursPerJobEntry;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.ComboBox versionComboBox;
	
	private global::Gtk.Button button5;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.Button button8;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.Label label12;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView logWindow;
	
	private global::Gtk.HBox hbox11;
	
	private global::Gtk.Button button7;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.Label label13;
	
	private global::Gtk.Label label14;
	
	private global::Gtk.HBox hbox10;
	
	private global::Gtk.Button button6;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.VBox vbox7;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TextView helpWindow;
	
	private global::Gtk.Label label15;
	
	private global::Gtk.Statusbar statusbar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 3;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = "Run on QRIS-HPC";
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = "Username";
		this.table1.Add (this.label5);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = "Password";
		this.table1.Add (this.label6);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.password = new global::Gtk.Entry ();
		this.password.CanFocus = true;
		this.password.Name = "password";
		this.password.IsEditable = true;
		this.password.WidthChars = 10;
		this.password.Visibility = false;
		this.password.InvisibleChar = '●';
		this.table1.Add (this.password);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.password]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.username = new global::Gtk.Entry ();
		this.username.CanFocus = true;
		this.username.Name = "username";
		this.username.IsEditable = true;
		this.username.WidthChars = 10;
		this.username.InvisibleChar = '●';
		this.table1.Add (this.username);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.username]));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		this.hbox2.Add (this.table1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.table1]));
		w6.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.radiobutton1 = new global::Gtk.RadioButton ("tinaroo");
		this.radiobutton1.CanFocus = true;
		this.radiobutton1.Name = "radiobutton1";
		this.radiobutton1.DrawIndicator = true;
		this.radiobutton1.UseUnderline = true;
		this.radiobutton1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox4.Add (this.radiobutton1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.radiobutton1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.radiobutton2 = new global::Gtk.RadioButton ("awoonga");
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = this.radiobutton1.Group;
		this.vbox4.Add (this.radiobutton2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.radiobutton2]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox2.Add (this.vbox4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
		w9.Position = 2;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = "Filename";
		this.hbox4.Add (this.label7);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label7]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.fileEntry = new global::Gtk.Entry ();
		this.fileEntry.CanFocus = true;
		this.fileEntry.Name = "fileEntry";
		this.fileEntry.IsEditable = true;
		this.fileEntry.InvisibleChar = '●';
		this.hbox4.Add (this.fileEntry);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fileEntry]));
		w12.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = "Browse";
		this.hbox4.Add (this.button1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button1]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox4]));
		w14.Position = 0;
		this.vbox3.Add (this.hbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w16.Position = 0;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = "Directory";
		this.hbox5.Add (this.label8);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label8]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.dirEntry = new global::Gtk.Entry ();
		this.dirEntry.CanFocus = true;
		this.dirEntry.Name = "dirEntry";
		this.dirEntry.IsEditable = true;
		this.dirEntry.InvisibleChar = '●';
		this.hbox5.Add (this.dirEntry);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.dirEntry]));
		w19.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = "Browse";
		this.hbox5.Add (this.button2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.button2]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox1.Add (this.hbox5);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.simsPerJobEntry = new global::Gtk.Entry ();
		this.simsPerJobEntry.CanFocus = true;
		this.simsPerJobEntry.Name = "simsPerJobEntry";
		this.simsPerJobEntry.IsEditable = true;
		this.simsPerJobEntry.WidthChars = 4;
		this.simsPerJobEntry.MaxLength = 6;
		this.simsPerJobEntry.InvisibleChar = '●';
		this.hbox6.Add (this.simsPerJobEntry);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.simsPerJobEntry]));
		w22.Position = 0;
		w22.Expand = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulations / job");
		this.hbox6.Add (this.label9);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label9]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hoursPerJobEntry = new global::Gtk.Entry ();
		this.hoursPerJobEntry.CanFocus = true;
		this.hoursPerJobEntry.Name = "hoursPerJobEntry";
		this.hoursPerJobEntry.IsEditable = true;
		this.hoursPerJobEntry.WidthChars = 4;
		this.hoursPerJobEntry.MaxLength = 6;
		this.hoursPerJobEntry.InvisibleChar = '●';
		this.hbox6.Add (this.hoursPerJobEntry);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.hoursPerJobEntry]));
		w24.Position = 2;
		w24.Expand = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Machine Hours / job");
		this.hbox6.Add (this.label11);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label11]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox1.Add (this.hbox6);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
		w26.Position = 3;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = "Version";
		this.hbox8.Add (this.label10);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label10]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		this.vbox1.Add (this.hbox8);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox8]));
		w28.Position = 4;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.versionComboBox = global::Gtk.ComboBox.NewText ();
		this.versionComboBox.WidthRequest = 250;
		this.versionComboBox.Name = "versionComboBox";
		this.hbox9.Add (this.versionComboBox);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.versionComboBox]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Update");
		this.hbox9.Add (this.button5);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button5]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox1.Add (this.hbox9);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox9]));
		w31.Position = 5;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = "Cancel";
		this.hbox7.Add (this.button3);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button3]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button ();
		this.button8.Sensitive = false;
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString ("Resume");
		this.hbox7.Add (this.button8);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button8]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = "Go";
		this.hbox7.Add (this.button4);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button4]));
		w34.Position = 2;
		w34.Expand = false;
		w34.Fill = false;
		this.vbox1.Add (this.hbox7);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
		w35.Position = 6;
		w35.Expand = false;
		w35.Fill = false;
		this.notebook1.Add (this.vbox1);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Setup");
		this.notebook1.SetTabLabel (this.vbox1, this.label2);
		this.label2.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = "Run on QRIS-HPC";
		this.vbox5.Add (this.label12);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label12]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.logWindow = new global::Gtk.TextView ();
		this.logWindow.CanFocus = true;
		this.logWindow.Name = "logWindow";
		this.logWindow.Editable = false;
		this.GtkScrolledWindow.Add (this.logWindow);
		this.vbox5.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow]));
		w39.Position = 1;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button ();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString ("Save log");
		this.hbox11.Add (this.button7);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.button7]));
		w40.Position = 0;
		w40.Fill = false;
		this.vbox5.Add (this.hbox11);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox11]));
		w41.Position = 2;
		w41.Expand = false;
		w41.Fill = false;
		this.notebook1.Add (this.vbox5);
		global::Gtk.Notebook.NotebookChild w42 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox5]));
		w42.Position = 1;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Progress");
		this.notebook1.SetTabLabel (this.vbox5, this.label3);
		this.label3.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = "Run on QRIS-HPC";
		this.vbox6.Add (this.label13);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label13]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Job in preparation");
		this.vbox6.Add (this.label14);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label14]));
		w44.Position = 1;
		w44.Expand = false;
		w44.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.Sensitive = false;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("Download outputs");
		this.hbox10.Add (this.button6);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.button6]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		this.vbox6.Add (this.hbox10);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox10]));
		w46.Position = 2;
		w46.Expand = false;
		w46.Fill = false;
		this.notebook1.Add (this.vbox6);
		global::Gtk.Notebook.NotebookChild w47 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox6]));
		w47.Position = 2;
		// Notebook tab
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Download");
		this.notebook1.SetTabLabel (this.vbox6, this.label4);
		this.label4.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.helpWindow = new global::Gtk.TextView ();
		this.helpWindow.CanFocus = true;
		this.helpWindow.Name = "helpWindow";
		this.helpWindow.Editable = false;
		this.GtkScrolledWindow1.Add (this.helpWindow);
		this.vbox7.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.GtkScrolledWindow1]));
		w49.Position = 0;
		this.notebook1.Add (this.vbox7);
		global::Gtk.Notebook.NotebookChild w50 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox7]));
		w50.Position = 3;
		// Notebook tab
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Help");
		this.notebook1.SetTabLabel (this.vbox7, this.label15);
		this.label15.ShowAll ();
		this.vbox2.Add (this.notebook1);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook1]));
		w51.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.statusbar = new global::Gtk.Statusbar ();
		this.statusbar.Name = "statusbar";
		this.statusbar.Spacing = 6;
		this.vbox2.Add (this.statusbar);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.statusbar]));
		w52.Position = 1;
		w52.Expand = false;
		w52.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 413;
		this.DefaultHeight = 385;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.notebook1.SelectPage += new global::Gtk.SelectPageHandler (this.OnNotebook1SelectPage);
		this.button1.Clicked += new global::System.EventHandler (this.onChooseFile);
		this.button2.Clicked += new global::System.EventHandler (this.onChooseDirectory);
		this.button3.Clicked += new global::System.EventHandler (this.OnCancelEvent);
	}
}
