include $(APSIM)/Model/Build/Platform.make

PROJECT = PastureScienceConverter

SRC = PastureScienceConverter.cpp PastureConverter.cpp PastureUptake.cpp ..\ComponentInterface\EntryPoints.cpp
LIBS = General ApsimShared ComponentInterface

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make


