include $(APSIM)/Model/Build/Platform.make

PROJECT = PastureScienceConverter

SRC = PastureScienceConverter.cpp PastureConverter.cpp PastureUptake.cpp
LIBS = General ApsimShared ComponentInterface
OBJS = $(APSIM)/Model/ComponentInterface/EntryPoints.obj

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make


