include $(APSIM)/Model/Build/Platform.make

PROJECT = Protocol

SRC = Protocol.cpp Transport.cpp Computation.cpp

LIBS = General ApsimShared
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make
