include $(APSIM)/Model/Build/Platform.make

PROJECT = Apsim

SRC = ApsimMain.cpp Simulation.cpp ../ComponentInterface/message.cpp

LIBS = ApsimShared General Protocol

PROJECTTYPE = exe

include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

