include $(APSIM)/Model/Build/Platform.make

ifeq ($(PLATFORM),Linux)
PROJECT = SoilNitrogen
else
PROJECT = SoilNitrogen
endif

PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)DOTNET.make
