include $(APSIM)/Model/Build/Platform.make

PROJECT = Input

SRC = Input.cpp InputComponent.cpp StringVariant.cpp 
LIBS = General ApsimShared ComponentInterface 
OBJS = $(APSIM)/Model/ComponentInterface/EntryPoints.obj
PROJECTTYPE = dll



include $(APSIM)/Model/Build/$(PLATFORM)CPP.make

