include $(APSIM)/Model/Build/Platform.make

PROJECT = SWIM3

SRC = Registrations.f90 SWIM3.for
STATICLIBS = FortranInfrastructure
LIBS = FortranComponentInterface

APSIMMODEL = Yes
PROJECTTYPE = dll

include $(APSIM)/Model/Build/$(PLATFORM)FOR.make
